### ISSUE TITLE
It Doesn't Work

### ISSUE THREAD

**Issue by mawendir** [MangaD/mybb-thread-preview#1]
Followed the tutorial but it doesn't work. I've not missed anything or done anything wrong, I think. In the forum display page I only see topics names and onmouseover="make_visible(25)" onmouseout="make_hidden(25)" besides them. Running freshly installed 1.8.27 with no other mods other than this one.

**Comment by MangaD** [comment]
From what you describe, it appears that during step 3 you have put the code not as attributes of the tag but as their content. The HTML should look like this:
```html
<a href="{$thread['threadlink']}" onmouseover="make_visible({$thread['tid']})" onmouseout="make_hidden({$thread['tid']})">{$thread['subject']}</a>
```

**Comment by mawendir** [comment]
Thank you, my bad, quite sleepy so didn't get what you meant in the first place. That makes the job done pretty well.
